### ISSUE TITLE
Secrets Sync not seeming to be working for OCI provider

### ISSUE THREAD

**Issue by marc-brouard** [oracle-samples/oci-secrets-store-csi-driver-provider#7]
In the getting started documentation (GettingStarted.md) it mentions under Additional Features, Secrets Sync, that it "allows the driver to create a Kubernetes Secret to mirror the mounted content". This does not seem to be working. Following the documentation, I have the following yaml file
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pdavault
spec:
  provider: oci
  secretObjects:
  - secretName: pda-config
    type: Opaque
    data:
    - objectName: PDA_DB_USER
      key: PDA_DB_USER
  parameters:
    secrets: |
      - name: PDA_DB_USER
        stage: LATEST
    authType: instance
    vaultId: ocid1.vault.oc1.blahblah
```
The secret is not created, have I got this configuration wrong or does the oci provider not support this?

**Comment by shukawam** [comment]
I hace a same problem. I did the installation as follows, but the Secret is not created.

```values.oke.yaml
provider:
  image:
    repository: ghcr.io/oracle-samples/oci-secrets-store-csi-driver-provider
secrets-store-csi-driver:
  install: true
  syncSecret:
    enabled: true
  enableSecretRotation: true
  rotationPollInterval: 1m
```

install.

```bash
helm -n kube-system install oci-provider oci-provider/oci-secrets-store-csi-driver-provider -f values.oke.yaml
```

Then, apply this manifest.

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datasource-secret-provider
  namespace: backend
spec:
  provider: oci
  secretObjects:
    - secretName: datasource-secret
      type: Opaque
  parameters:
    secrets: |
      - name: datasource.url
        stage: LATEST
      - name: datasource.username
        stage: LATEST
      - name: datasource.password
        stage: LATEST
    authType: instance
    vaultId: ocid1.vault.oc1.ap-osaka-1...

```

**Comment by rajashekhargundeti** [comment]
@shukawam ,

secretObjects should mention which of the mounted secrets to go into k8s secret. If data is empty, k8s secret wont be created.

here is an example:

```
  secretObjects:
    - data:
        - key: db-password
          objectName: vault-1-secret-2
      secretName: k8s-secret
      type: Opaque
```

Please check provider and driver logs on that particular worker node, you might notice something like below:

```
E0315 07:03:32.537190       1 secretproviderclasspodstatus_controller.go:292] "failed to validate secret object in spc" err="data is empty" spc="default/instance-auth-spc" pod="default/nginx-5f5f78d689-phqhs" spcps="default/nginx-5f5f78d689-phqhs-default-instance-auth-spc"
I0315 07:03:33.817945       1 secretproviderclasspodstatus_controller.go:222] "reconcile started" spcps="default/nginx-5f5f78d689-phqhs-default-instance-auth-spc"
```
